---
title: "A Pan Cancer Atlas"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
setwd("~/desktop/THCA")
ex <- read.delim("~/Desktop/THCA/ex_LUAD.tsv")
cn <- ex #backup

rownames(cn) <- cn$gene_id
cn <- cn[,-1:-2]

# Duplicated Counts from patients
cn <- cn[,-c(178,223,226,246,339,428,485,474)]
```


```{r}
#sample types
library(dplyr)
sampleID <- read.delim("~/desktop/THCA/TCGA-LUAD/Data/gdc_sample_sheet.2022-06-11.tsv")
i1 <- sampleID$Data.Type == "Gene Expression Quantification"
sampleID <- sampleID[i1, , drop = F]
sampleID <- sampleID[,7:8]
sampleID <- distinct(sampleID, Sample.ID, .keep_all = T)
a <- colnames(cn)
for(i in 1:3){a <- sub('\\.', '-', a)}
b <- data.frame(IDs = a)
c <- merge(b, sampleID, by.x = "IDs", by.y = "Sample.ID", sort = F)
cc <- data.frame(sample = sub("Primary Tumor", "PRT", c$Sample.Type))
cc <- data.frame(sample = sub("Solid Tissue Normal", "STN", cc$sample))
for(i in 1:3){c$IDs <- sub('\\-', '.', c$IDs)}
colnames(cn) <- cc$sample
head(cn)
# we reached to our tidy data set

```
```{r}
library(DESeq2)
con <- factor(paste0(c$Sample.Type, seq_along(c$Sample.Type)))
gr <- factor(cc$sample)
#colSums(cn)
colData <- data.frame(condition = con,group = gr , type = "paired-end")
cds <- DESeqDataSetFromMatrix(cn, colData, design = ~group) 
cds <- DESeq(cds) #Constructing DESeq2  dataset
cnt <- log2(1+(counts(cds, normalize = T))) #getting normalized counts `count matrix`
```

